import { memo, useCallback } from "react";
import type { AINote } from "@/types";
import { useDownloadPdf, useDownloadDocx, useCopyToClipboard } from "@/services/export.service";
import { useToast } from "@/components/ui/Toast";
import { Button } from "@/components/ui/Button";

interface AINoteCardProps {
  note: AINote;
  onClick?: () => void;
  showFullContent?: boolean;
  showExportButtons?: boolean;
}

export const AINoteCard = memo(function AINoteCard({
  note,
  onClick,
  showFullContent = false,
  showExportButtons = false,
}: AINoteCardProps) {
  const { addToast } = useToast();
  const { downloadPdf, loading: pdfLoading } = useDownloadPdf();
  const { downloadDocx, loading: docxLoading } = useDownloadDocx();
  const { copyToClipboard, loading: copyLoading } = useCopyToClipboard();

  const handleDownloadPdf = useCallback(async (e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      await downloadPdf(note.id, note.title || "notes");
      addToast("PDF downloaded successfully!", "success");
    } catch {
      addToast("Failed to download PDF", "error");
    }
  }, [downloadPdf, note.id, note.title, addToast]);

  const handleDownloadDocx = useCallback(async (e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      await downloadDocx(note.id, note.title || "notes");
      addToast("DOCX downloaded successfully!", "success");
    } catch {
      addToast("Failed to download DOCX", "error");
    }
  }, [downloadDocx, note.id, note.title, addToast]);

  const handleCopy = useCallback(async (e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      await copyToClipboard(note);
      addToast("Notes copied to clipboard!", "success");
    } catch {
      addToast("Failed to copy to clipboard", "error");
    }
  }, [copyToClipboard, note, addToast]);

  const exportLoading = pdfLoading || docxLoading || copyLoading;

  return (
    <div
      onClick={onClick}
      role={onClick ? "button" : undefined}
      tabIndex={onClick ? 0 : undefined}
      onKeyDown={onClick ? (e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); onClick(); } } : undefined}
      className={`group rounded-2xl border border-gray-200 bg-white shadow-sm transition-all duration-200 hover:shadow-md dark:border-gray-800 dark:bg-gray-900 ${
        onClick ? "cursor-pointer" : ""
      }`}
    >
      {/* Header */}
      <div className="border-b border-gray-200 p-4 sm:p-6 dark:border-gray-800">
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0 flex-1">
            <h3 className="text-base sm:text-lg font-semibold text-gray-900 dark:text-white truncate">
              {note.title}
            </h3>
            <div className="mt-1.5 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs sm:text-sm text-gray-500 dark:text-gray-400">
              <span>{new Date(note.created_at).toLocaleDateString()}</span>
              {note.model_used && (
                <>
                  <span aria-hidden="true">•</span>
                  <span>Generated by {note.model_used}</span>
                </>
              )}
              {note.processing_time > 0 && (
                <>
                  <span aria-hidden="true">•</span>
                  <span>{note.processing_time.toFixed(1)}s</span>
                </>
              )}
            </div>
          </div>
          <span className="flex-shrink-0 rounded-full bg-primary-100 px-2.5 py-1 text-xs font-medium text-primary-700 dark:bg-primary-900/50 dark:text-primary-300">
            AI Notes
          </span>
        </div>
      </div>

      {/* Content */}
      <div className="p-4 sm:p-6">
        {/* Executive Summary */}
        {note.executive_summary && (
          <div className="mb-5">
            <h4 className="mb-2 flex items-center gap-2 text-sm font-semibold text-gray-900 dark:text-white">
              <span aria-hidden="true">📋</span>
              <span>Executive Summary</span>
            </h4>
            <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
              {note.executive_summary}
            </p>
          </div>
        )}

        {/* Key Concepts */}
        {note.key_concepts && note.key_concepts.length > 0 && (
          <div className="mb-5">
            <h4 className="mb-2 flex items-center gap-2 text-sm font-semibold text-gray-900 dark:text-white">
              <span aria-hidden="true">💡</span>
              <span>Key Concepts</span>
            </h4>
            <div className="flex flex-wrap gap-1.5">
              {note.key_concepts.map((concept, idx) => (
                <span
                  key={idx}
                  className="inline-flex items-center rounded-full bg-blue-50 px-2.5 py-1 text-xs font-medium text-blue-700 transition-colors hover:bg-blue-100 dark:bg-blue-900/30 dark:text-blue-300 dark:hover:bg-blue-900/50"
                >
                  {concept}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Detailed Notes */}
        {note.detailed_notes && (
          <div className="mb-5">
            <h4 className="mb-2 flex items-center gap-2 text-sm font-semibold text-gray-900 dark:text-white">
              <span aria-hidden="true">📝</span>
              <span>Detailed Notes</span>
            </h4>
            <div className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
              {showFullContent ? (
                <div className="whitespace-pre-wrap">{note.detailed_notes}</div>
              ) : (
                <div className="line-clamp-6 whitespace-pre-wrap">
                  {note.detailed_notes}
                </div>
              )}
            </div>
          </div>
        )}

        {/* Bullet Points */}
        {note.bullet_points && note.bullet_points.length > 0 && (
          <div className="mb-5">
            <h4 className="mb-2 flex items-center gap-2 text-sm font-semibold text-gray-900 dark:text-white">
              <span aria-hidden="true">✅</span>
              <span>Key Takeaways</span>
            </h4>
            <ul className="space-y-1.5">
              {note.bullet_points.map((point, idx) => (
                <li key={idx} className="flex items-start gap-2 text-sm text-gray-600 dark:text-gray-400">
                  <span className="mt-1 flex-shrink-0 text-primary-500" aria-hidden="true">•</span>
                  <span>{point}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Keywords */}
        {note.keywords && note.keywords.length > 0 && (
          <div className="mb-5">
            <h4 className="mb-2 flex items-center gap-2 text-sm font-semibold text-gray-900 dark:text-white">
              <span aria-hidden="true">🏷️</span>
              <span>Keywords</span>
            </h4>
            <div className="flex flex-wrap gap-1.5">
              {note.keywords.map((keyword, idx) => (
                <span
                  key={idx}
                  className="inline-flex items-center rounded-full bg-gray-100 px-2.5 py-1 text-xs font-medium text-gray-700 transition-colors hover:bg-gray-200 dark:bg-gray-800 dark:text-gray-300 dark:hover:bg-gray-700"
                >
                  {keyword}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Action Items */}
        {note.action_items && note.action_items.length > 0 && (
          <div className="mb-5">
            <h4 className="mb-2 flex items-center gap-2 text-sm font-semibold text-gray-900 dark:text-white">
              <span aria-hidden="true">🎯</span>
              <span>Action Items</span>
            </h4>
            <ul className="space-y-1.5">
              {note.action_items.map((item, idx) => (
                <li key={idx} className="flex items-start gap-2 text-sm text-gray-600 dark:text-gray-400">
                  <span className="mt-1 flex-shrink-0 text-green-500" aria-hidden="true">☐</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Conclusion */}
        {note.conclusion && (
          <div className="rounded-xl bg-gray-50 p-4 transition-colors hover:bg-gray-100 dark:bg-gray-800/50 dark:hover:bg-gray-800">
            <h4 className="mb-2 flex items-center gap-2 text-sm font-semibold text-gray-900 dark:text-white">
              <span aria-hidden="true">📌</span>
              <span>Conclusion</span>
            </h4>
            <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
              {note.conclusion}
            </p>
          </div>
        )}

        {/* Export Buttons */}
        {showExportButtons && (
          <div className="mt-6 border-t border-gray-200 pt-5 dark:border-gray-800">
            <div className="flex flex-wrap items-center gap-2">
              <Button
                variant="secondary"
                size="sm"
                loading={pdfLoading}
                disabled={exportLoading}
                onClick={handleDownloadPdf}
                icon={
                  <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
                  </svg>
                }
              >
                PDF
              </Button>
              <Button
                variant="secondary"
                size="sm"
                loading={docxLoading}
                disabled={exportLoading}
                onClick={handleDownloadDocx}
                icon={
                  <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                }
              >
                DOCX
              </Button>
              <Button
                variant="secondary"
                size="sm"
                loading={copyLoading}
                disabled={exportLoading}
                onClick={handleCopy}
                icon={
                  <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                  </svg>
                }
              >
                Copy
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
});
